"""
code_generator.py — Mini-C → Python Code Generator  (Member 3)
Visitor-pattern walker over annotated AST nodes.
Emits correct, indented Python code for each Mini-C construct.
"""

from ast_nodes import (
    Program, FunctionDecl, Param, VarDecl, Block,
    IfStmt, WhileStmt, ReturnStmt, ExprStmt,
    Assign, BinaryOp, UnaryOp, Literal, Identifier, FunctionCall, ASTNode,
)
from typing import List


# Type hint map
TYPE_MAP = {"int": "int", "float": "float", "void": "None", "bool": "bool", "string": "str"}

# Binary operator pass-through (Mini-C uses same symbols as Python for most)
OP_MAP = {"&&": "and", "||": "or", "!": "not", "==": "==", "!=": "!=",
          "<": "<", ">": ">", "<=": "<=", ">=": ">=",
          "+": "+", "-": "-", "*": "*", "/": "//"}


class CodeGenError(Exception):
    pass


class CodeGenerator:
    def __init__(self):
        self._indent = 0
        self._lines: List[str] = []
        self._has_main = False

    def _emit(self, text: str = ""):
        prefix = "    " * self._indent
        self._lines.append(prefix + text)

    def generate(self, node: ASTNode) -> str:
        self._lines = []
        self._indent = 0
        self._emit("# Generated by Mini-C → Python Compiler")
        self._emit("from __future__ import annotations")
        self._emit()
        self._visit(node)
        if self._has_main:
            self._emit()
            self._emit('if __name__ == "__main__":')
            self._indent += 1
            self._emit("main()")
            self._indent -= 1
        return "\n".join(self._lines)

    # ── Dispatcher ────────────────────────────────────────────────────────────
    def _visit(self, node: ASTNode) -> str:
        method = getattr(self, f"_visit_{type(node).__name__}", self._visit_default)
        return method(node)

    def _visit_default(self, node: ASTNode) -> str:
        raise CodeGenError(f"No visitor for {type(node).__name__}")

    # ── Top-level ─────────────────────────────────────────────────────────────
    def _visit_Program(self, node: Program):
        for decl in node.declarations:
            self._visit(decl)
            self._emit()

    def _visit_FunctionDecl(self, node: FunctionDecl):
        if node.name == "main":
            self._has_main = True
        params = ", ".join(
            f"{p.name}: {TYPE_MAP.get(p.var_type, p.var_type)}" for p in node.params
        )
        ret = TYPE_MAP.get(node.return_type, node.return_type)
        self._emit(f"def {node.name}({params}) -> {ret}:")
        self._indent += 1
        if node.body:
            self._visit_Block_body(node.body)
        else:
            self._emit("pass")
        self._indent -= 1

    # ── Statements ────────────────────────────────────────────────────────────
    def _visit_Block(self, node: Block):
        self._visit_Block_body(node)

    def _visit_Block_body(self, node: Block):
        if not node.statements:
            self._emit("pass")
        else:
            for stmt in node.statements:
                self._visit(stmt)

    def _visit_VarDecl(self, node: VarDecl):
        hint = TYPE_MAP.get(node.var_type, node.var_type)
        if node.value:
            val = self._expr(node.value)
            self._emit(f"{node.name}: {hint} = {val}")
        else:
            # default initializer
            defaults = {"int": "0", "float": "0.0", "bool": "False", "string": '""'}
            self._emit(f"{node.name}: {hint} = {defaults.get(node.var_type, 'None')}")

    def _visit_IfStmt(self, node: IfStmt):
        cond = self._expr(node.condition) if node.condition else "True"
        self._emit(f"if {cond}:")
        self._indent += 1
        if node.then:
            self._visit_Block_body(node.then) if isinstance(node.then, Block) else self._visit(node.then)
        else:
            self._emit("pass")
        self._indent -= 1
        if node.else_:
            if isinstance(node.else_, IfStmt):
                self._emit_elif(node.else_)
            else:
                self._emit("else:")
                self._indent += 1
                self._visit_Block_body(node.else_) if isinstance(node.else_, Block) else self._visit(node.else_)
                self._indent -= 1

    def _emit_elif(self, node: IfStmt):
        cond = self._expr(node.condition) if node.condition else "True"
        self._emit(f"elif {cond}:")
        self._indent += 1
        if node.then:
            self._visit_Block_body(node.then) if isinstance(node.then, Block) else self._visit(node.then)
        else:
            self._emit("pass")
        self._indent -= 1
        if node.else_:
            if isinstance(node.else_, IfStmt):
                self._emit_elif(node.else_)
            else:
                self._emit("else:")
                self._indent += 1
                self._visit_Block_body(node.else_) if isinstance(node.else_, Block) else self._visit(node.else_)
                self._indent -= 1

    def _visit_WhileStmt(self, node: WhileStmt):
        cond = self._expr(node.condition) if node.condition else "True"
        self._emit(f"while {cond}:")
        self._indent += 1
        if node.body:
            self._visit_Block_body(node.body) if isinstance(node.body, Block) else self._visit(node.body)
        else:
            self._emit("pass")
        self._indent -= 1

    def _visit_ReturnStmt(self, node: ReturnStmt):
        if node.value:
            self._emit(f"return {self._expr(node.value)}")
        else:
            self._emit("return")

    def _visit_ExprStmt(self, node: ExprStmt):
        if node.expr:
            self._emit(self._expr(node.expr))

    def _visit_Block_direct(self, node):
        """Used when a block appears as a statement (not function body)."""
        for stmt in node.statements:
            self._visit(stmt)

    # ── Expression emitter (returns string) ──────────────────────────────────
    def _expr(self, node: ASTNode) -> str:
        method = getattr(self, f"_expr_{type(node).__name__}", None)
        if method is None:
            raise CodeGenError(f"No expr visitor for {type(node).__name__}")
        return method(node)

    def _expr_Literal(self, node: Literal) -> str:
        if isinstance(node.value, bool):
            return "True" if node.value else "False"
        if isinstance(node.value, str):
            return repr(node.value)
        return str(node.value)

    def _expr_Identifier(self, node: Identifier) -> str:
        return node.name

    def _expr_BinaryOp(self, node: BinaryOp) -> str:
        left = self._expr(node.left)
        right = self._expr(node.right)
        op = OP_MAP.get(node.op, node.op)
        # Add parens if sub-expression is also BinaryOp (for clarity)
        if isinstance(node.left, BinaryOp):
            left = f"({left})"
        if isinstance(node.right, BinaryOp):
            right = f"({right})"
        return f"{left} {op} {right}"

    def _expr_UnaryOp(self, node: UnaryOp) -> str:
        op = OP_MAP.get(node.op, node.op)
        operand = self._expr(node.operand)
        return f"{op} {operand}"

    def _expr_Assign(self, node: Assign) -> str:
        return f"{node.name} = {self._expr(node.value)}"

    def _expr_FunctionCall(self, node: FunctionCall) -> str:
        args = ", ".join(self._expr(a) for a in node.args)
        return f"{node.name}({args})"

    def _visit_Assign(self, node: Assign):
        self._emit(f"{node.name} = {self._expr(node.value)}")


def generate(ast_root: ASTNode) -> str:
    return CodeGenerator().generate(ast_root)
